const router = require("express").Router();

const adminsRouter = require("./admins.routes");
const brandsRouter = require("./brands.routes");
const cartItemsRouter = require("./cartItems.routes");
const cartsRouter = require("./carts.routes");
const categoriesRouter = require("./categories.routes");
const colorsRouter = require("./colors.routes");
const contractItemsRouter = require("./contractItems.routes");
const contractStatusesRouter = require("./contractStatuses.routes");
const contractsRouter = require("./contracts.routes");
const couponsRouter = require("./coupons.routes");
const customerCouponsRouter = require("./customerCoupons.routes");
const customersRouter = require("./customers.routes");
const discountsRouter = require("./discounts.routes");
const feedbacksRouter = require("./feedbacks.routes");
const imagesRouter = require("./images.routes");
const installmentPlansRouter = require("./installmentPlans.routes");
const paymentMethodsRouter = require("./paymentMethods.routes");
const paymentStatusesRouter = require("./paymentStatuses.routes");
const paymentsRouter = require("./payments.routes");
const productDiscountsRouter = require("./productDiscounts.routes");
const productsRouter = require("./products.routes");
const functionsRouter = require("./functions.routes");

router.use("/admins", adminsRouter);
router.use("/brands", brandsRouter);
router.use("/cartItems", cartItemsRouter);
router.use("/carts", cartsRouter);
router.use("/categories", categoriesRouter);
router.use("/colors", colorsRouter);
router.use("/contractItems", contractItemsRouter);
router.use("/contractStatuses", contractStatusesRouter);
router.use("/contracts", contractsRouter);
router.use("/coupons", couponsRouter);
router.use("/customerCoupons", customerCouponsRouter);
router.use("/customers", customersRouter);
router.use("/discounts", discountsRouter);
router.use("/feedbacks", feedbacksRouter);
router.use("/images", imagesRouter);
router.use("/installmentPlans", installmentPlansRouter);
router.use("/paymentMethods", paymentMethodsRouter);
router.use("/paymentStatuses", paymentStatusesRouter);
router.use("/payments", paymentsRouter);
router.use("/productDiscounts", productDiscountsRouter);
router.use("/products", productsRouter);
router.use("/functions", functionsRouter);

module.exports = router;
